language: node_js
node_js:
  - "4"
cache:
  directories:
  - node_modules
  - bower_components
before_script:
  - make build
script:
  - hack/test-headless.sh test
  - hack/verify-dist.sh
                                                                                                                                        
